global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitryappnext'